### PR TITLE
Add .NET 6 minimal API example

### PR DESCRIPTION
**Pull request by cartermp**
Fixes https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/issues/134

### CODE REVIEW

**Comment by cartermp** [comment]
Argh, I don't think circleCI has an up to date .NET image :(

> Creating a dedicated VM with windows-server-2019-vs2019:stable image

Since it relies on visual studio-based images rather than just pulling in the .NET docker image, it might be more complicated to support .NET 6 in this repo

**Comment by bdarfler** [comment]
@cartermp maybe we need a custom docker image? https://circleci.com/docs/2.0/custom-images/

**Comment by cartermp** [comment]
will probably do this later, circle is still taking their time

**Comment by cartermp** [comment]
whelp https://discuss.circleci.com/t/cant-see-to-find-an-orb-with-support-for-dotnet-6/42652/4

Looks like Circle still haven't updated any orbs to support .NET 6, the LTS that's been out since November 2021.

Contemplating using the workaround posted in the form like there so we have samples using the LTS release when we go GA.

**Pull request closed without merging**
